---
 - hosts: jenkins
   become: yes
   remote_user: ec2-user
   become_user: root
   tasks:
     - name: Download Long Term Jenkins release
       #get_url:
         #url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
         #dest: /etc/yum.repos.d/jenkins.repo
       sudo wget -O /etc/yum.repos.d/jenkins.repo \
    https://pkg.jenkins.io/redhat-stable/jenkins.repo

     - name: Import jenkins key from url
       ansible.builtin.rpm_key:
         state: present
         key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

     - name: yum update
       yum:
         name: '*'
         state: latest

     - name: Install java
       yum:
         name: java-11-openjdk-devel
         state: present

     - name: Install jenkins
       yum:
         name: jenkins
         state: latest

     - name: daemon-reload to pick up config changes
       ansible.builtin.systemd:
         daemon_reload: yes

     - name: Start jenkins
       ansible.builtin.systemd:
         name: jenkins
         state: started
